# Generated by Django 3.2.16 on 2022-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='message_body',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
